[package]
name = "test_game_derive"
version = "0.1.0"
authors = ["PersonTheCat <33143148+PersonTheCat@users.noreply.github.com>"]
edition = "2018"

[lib]

proc-macro = true

[dependencies]

syn = { version = "*", features = ["derive"] }
quote = "*"
proc-macro2 = "*"