[package]
name = "test_game_client"
version = "0.1.0"
authors = ["PersonTheCat <33143148+PersonTheCat@users.noreply.github.com>"]
edition = "2018"

[dependencies]

lazy_static = "1.2.0"
parking_lot = "0.6.0"